### PR TITLE
Fix and update coordinate transformations

### LINKED ISSUE #29: Singularity at south pole not handled in geodetic calculation
The conversion to geodetic (GDZ) coordinates blows up when evaluated at the south pole.
This was reported by a SpacePy user who encountered the issue in our `coordinates` module, using IRBEM as the backend for the conversions.

### Minimal example to reproduce issue:
To demonstrate using the IRBEM Python package (rather than SpacePy):
```
import IRBEM
import datetime as dt
import numpy as np

cc = IRBEM.Coords()
tt = dt.datetime.now()  # time is irrelevant for a GEO spherical to GDZ conversion
pos = np.array([[1.063871355909377, -90.0, 360.0], [1.063871355909377, -90.0, 0.0], [1.063871355909377, 90.0, 180.0]])
cc.coords_transform([tt]*3, pos, 'SPH', 'GDZ')
```
See spacepy/spacepy#577 for the initial report, a reproduction through both our `Coords` objects and our low-level wrapping, and additional discussion.

The returned geodetic (altitude, latitude, longitude), which should have units of [km, deg, deg], is:
```
array([[-1.31195190e+04, -9.00000000e+01, -1.40334186e-14],
       [-1.31195190e+04, -9.00000000e+01,  0.00000000e+00],
       [ 4.06014389e+02,  9.00000000e+01,  1.80000000e+02]])
```
The altitude returned for the first two positions (both at the southern pole) are clearly incorrect. The altitudes should all be the same, as noted in spacepy/spacepy#296 (scroll to the bottom, there's a ton of discussion), this can be handled correctly in the geodetic algorithm.

### OS, IRBEM version, and compiler version information:
(One of my test setups listed here, but this is an algorithm/implementation issue and is platform-independent)
Ubuntu 20.04
Latest commit: a4759c0 (as used in last release of SpacePy); 1ceaca6 (problem reproducible on latest commit)
gfortran 9.3.0

### Source of IRBEM library
Git repo & via SpacePy

### Suggested resolution
The easiest fix is probably adding an explicit trap in the `geo_gdz` subroutine (starts on line 1529 of `init_nouveau.f`). I will note that the iterative algorithm may not be either the fastest or the most accurate these days, so it may also be worth considering a change to a more modern algorithm.

### LINKED ISSUE #31: SPH2CAR in Mead_Tsyganenko.f no longer exists.
Incorrect subroutine used in conversion from spherical to cartesian coordinates in Mead_Tsyganenko.f, line 39. Should be:
		CALL SPH_CAR(Bval,lati,longi,BMAG)
instead of 
		CALL SPH2CAR(Bval,lati,longi,BMAG)

Particularly since the SPH2CAR has been deleted from the onera_desp_lib.f file in change: https://github.com/PRBEM/IRBEM/pull/22

### PR DESCRIPTION
**Pull request by drsteve**
This PR addresses three main issues:
1. The conversions between the "old" coordinate systems (GEO, GEI, GSM, GDZ, etc.) and the more-recently-added systems (J2000, TOD) incorrectly assumes that GEI is equivalent to TEME. However, IRBEM's GEI is equivalent to TOD. See [this comment](https://github.com/spacepy/spacepy/issues/578#issuecomment-1059644395) for an explanation. Note that this also turned up the problem that GEI->TOD didn't work at all...
2. The GEO to GDZ conversion fails for southern polar coordinates. Closes #29 (but preserves the original algorithm, so still doesn't use an exact method)
3. There's a call to a renamed function in `Mead_Tsyganenko.f`. Closes #31 

The bulk of the changed code sets the equivalence between GEI and TOD in `CoordTrans.f`. This removes the incorrect transforms from GEI to TOD that impacted all of the transforms to both TOD and J2000 (from any system). This also fixes the GEI to TOD conversion as it now just returns the input.

While updating these transforms I added TEME as a supported system as it's useful for anyone using the SGP4 orbit propagator (which outputs in TEME).

The south pole is now explicitly trapped in `GEO_GDZ` with a correction to how the altitude is calculated for the southern pole.

The `SPH2CAR`call in `Mead_Tsyganenko.f` has been replaced with a call to `SPH_CAR`

#### PR Checklist
- [x] Pull request has descriptive title
- [x] Pull request gives overview of changes
- [x] New code has inline comments where necessary
- [x] Appropriate documentation has been written
- [x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by drsteve** [comment]
I know I've not checked the box for documentation, but I'm not really sure how the docs are being handled... I assume I need to update [https://github.com/PRBEM/IRBEM/blob/main/docs/frames/frames.html](https://github.com/PRBEM/IRBEM/blob/main/docs/frames/frames.html)?

The [current docs for the coordinates](https://prbem.github.io/IRBEM/frames/frames.html#COORDTRANSVEC) are a bit scant. The table covers ECITOD and J2000, but the direct transformation functions (e.g., `GEO2SM`) listed don't include the TEME/TOD/J2000 functions.
The [list of common arguments](https://prbem.github.io/IRBEM/frames/frames.html#COMMON_ARGUMENTS) includes a list of the numerical values for `sysaxes`, but this only runs 0 through 8 (i.e., doesn't include HEE, HAE, HEEQ, ECITOD, or J2000).

I can update all of that, but the docs also lead with "Version 4.4.0 - August 2012" - see [the introduction](https://prbem.github.io/IRBEM/frames/introduction.html). Presumably the top level info like that also needs updating? What are folks' preferences on this? Thoughts?

**Comment by AntoineBrunet** [comment]
Hi Steve, thanks for this PR. This is a great opportunity to update the documentation on the coordinates systems (maybe adding some references with the formal definitions of the different systems would help here). Yes, the `frames.html` file should be updated accordingly.

For the introduction to the documentation it is indeed significantly outdated. I think we could simply remove the header and replace it with a link to the Github repository, where all the information is already kept.

**Comment by drsteve** [comment]
I've overhauled the coordinates descriptions in `frames.html` and have done a rework of `introduction.html` to point folks to the GitHub repo. I've tried to not change or remove things without a reason, partly out of laziness and partly so that whoever has the unenviable task of modernizing the docs doesn't have to go digging for the history as much.

This should more than cover the docs requirements for the PR, so I've checked the box. If there's still anything that needs attention just let me know.

**Comment by drsteve** [comment]
Pinging this for review again... I'd really like to get this merged so #29 can be closed as it's impacting users (and SpacePy users). If there's anything else that I need to do please let me know.

**Review by mshumko — COMMENTED** [review]
I have not tested these changes, but most them look good.

I have one question: Now that SPH2CAR was changed to SPH_CAR, does the [idl_wrappers.c](https://github.com/drsteve/IRBEM/blob/6d1e18676fc1f9921036d97068fa45b0bfe4daf1/source/idl_wrappers.c#L106) also need to change?

**Comment by drsteve** [comment]
That's a good question. If it does need changing then it should already fail from the master branch (I just fixed where it was called from the Mead model). I have no convenient way of testing with IDL (and I have inconvenient ways of testing, but that'd have to wait a week or more).

The way I read it is that the IDL interface takes accepts the name `SPH2CAR` and then calls `SPH_CAR`. So it _should_ be fine.

**Comment by drsteve** [comment]
Commenting again to bump this as I'd really like to get the bugs fixed (particularly #29, but the others are also important). Anyone comfortable giving either an approving review (and merge?) or specific requested changes is very welcome to do so...

To give a concrete answer to the question about `SPH_CAR`/`SPH2CAR` in the IDL wrappers - yes the current wrappers are fine. The wrapper was made in #22 and incorporated that change. That PR missed the calls in `Mead_Tsyganenko.f`, hence #31.

**Comment by mshumko** [comment]
I have to admit that I am uncomfortable with the changes, primarily because as far as I'm aware, there are no automated tests to confirm that the coordinate transformations are working (or at least not in Python). 

I will approve this now, but we should add automated tests for the coordinate transforms. I can do that in Python when I get the time.

**Review by mshumko — APPROVED** [review]

**Comment by drsteve** [comment]
Understood, and thanks for the PR approval.
I do support the expansion of appropriate testing for IRBEM's CI. I will also note that there have never been tests for IRBEM to make sure the coordinate system transformations work, which is partly why this PR is necessary.

Just to be clear, this has been tested though... We have a fairly comprehensive test suite in SpacePy, which tests both our Python backend for coordinate transformations as well as coordinate transformations using IRBEM as the backend. There's a mix of regression tests, tests for expected behavior, and tests for consistency between different implementations. I have, of course, tested this with the SpacePy test suite and compared to reference transforms for the J2000-related changes. 

If it helps any, the actual code changes here are very minor. Inspection will show no change to the first 11 defined coordinate transforms. The _significant_ changes (still minimal code difference) are: 1. setting TOD (system 12) to be treated as equivalent to GEI (system 5); 2. removing the incorrect step of transforming from TEME to TOD on the way to J2000; and 3. making TEME a new coordinate system option (system 14, previously the max system was 13 and no systems have changed number). It looks like a lot of changed code because the changes need repeating for each input system...

**Comment by drsteve** [comment]
> To show the testing in our CI, I pushed these updates into the IRBEM source used in SpacePy and set up a draft PR ([spacepy/spacepy#631](https://github.com/spacepy/spacepy/pull/631)). Note that our (fairly extensive) test suite passes. Hopefully that helps...

I've now expanded the SpacePy test suite coverage of IRBEM's coordinate transforms to include both 1) consistency checks for TEME and 2) roundtrip testing for all natively Cartesian geocentric systems. The roundtrip testing ensures that all transforms are reversible and that they're all supported.
(The roundtrip testing did prompt an update of this PR to ensure that all input systems and output systems were, in fact, fully supported).

**Comment by drsteve** [comment]
Is there likely to be any progress on this?
Right now we're trying to get a new SpacePy release out and I'd really like to provide fixes to known issues with that. If no-one here will merge this I have two choices:
- Merge the PR here myself (I don't want to do this because I authored the PR and having someone else merge implies concurrence)
- Include these updates with SpacePy anyway (I don't want to do this because it diverges from the official repo)

So left with two options that I don't really like, I'm more inclined to take door number 1 and merge this PR myself because that fixes issues for direct IRBEM users in addition to SpacePy users. Any final comments? The window before the next SpacePy release is now _very_ short.

**Comment by mshumko** [comment]
@drsteve I wasn't aware that PR authors shouldn't merge their code after it was approved. In fact, the discussion in this [Stack Exchange](https://softwareengineering.stackexchange.com/questions/334488/code-review-workflow-where-pull-request-author-must-merge)  thread suggests that the PR author is the best person to merge their code.

**Comment by drsteve** [comment]
In my experience merging for PRs that touch code in a meaningful way is done by a reviewer (after 1 or more reviews). The arguments in the Stack Exchange thread about conflicts, CI, etc. don't hold up in my opinion: if there are conflicts that would prevent merge the author should fix those before the PR can be merged; if CI fails the PR needs fixing before merge. 

See, e.g., https://holgerfrohloff.de/best-practices-on-doing-pull-requests
> The merging should be done by the assigned reviewer. If there are multiple people responsible, you can talk about who should merge. It shouldn't be the author of the PR. Allowing the author to merge her own changes leads to a bad practice where people merge too quickly, without a proper review.

The principle of having extra eyes on, and having the reviewer have their name signed to the PR by merging it, is why the teams I've worked on/with generally avoid authors merging their own PRs. Some projects set up auto-merge as a time-saver, so that an approved PR that passes all appropriate testing is merged once all the required conditions are met (number of reviews/approvals, CI, no conflicts, ...)

I'd also point out [the Meltano handbook](https://handbook.meltano.com/engineering/merge-process) (Meltano is a gitlab-spinoff development platform) says
> For community contributions, the community contributor should indicate readiness to merge and the core team member (primary reviewer) will approve the PR and also perform the merge.

Ultimately it comes down to whatever the project wants to do though. And while I do have commit/merge privileges here, and a history with the library, I'm not an admin and wouldn't count myself as a "code owner". I'm still not entirely comfortable just unilaterally deciding that I can merge changes to IRBEM as an IRBEM-community contributor. If the PR had come from someone without merge privileges who does the merge?

Perhaps the contributor guidelines should be updated to be clearer on required reviews, who merges, etc.

**Pull request merged**
