### PR TITLE
Correct Makefile for the git migration

### PR DESCRIPTION
**Pull request by AntoineBrunet**
This PR modifies the Makefile to correct issues #3  and #4 .
It uses the `git describe` command to produce an appropriate label for the current release (either a tag name or the commit hash), and `git rev-list --count` as an equivalent of the revision number that was used in SVN.
The issues with `myOwnMagneticField` were resolved by not removing the files if the user-supplied directory does not exist.

- [x] Pull request has descriptive title
- [x] Pull request gives overview of changes
- [x] New code has inline comments where necessary
- [x] Appropriate documentation has been written
- [x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Review by mshumko — CHANGES_REQUESTED** [review]
Hi Antoine, 

I pulled your PR code and the `make OS=linux64 ENV=gnu64 all` command finishes. However, I get the following error that are both due to LAndI2Lstar.f (it shows up twice for the non-shareable and the shareable object builds) 

```shell
$ make OS=linux64 ENV=gnu64 all
Current version: faba921 (319)
Building non-sharable object onera_desp_lib_linux_x86_64.a
LAndI2Lstar.f:20680:19:

20680 |      &             maginput_tmp,Lm_tmp,XJ_tmp,Lstar_tmp)
      |                   1
Error: Actual argument contains too few elements for dummy argument 'maginput' (25/2500000) at (1)
ar: creating liboneradesp_linux_x86_64.a
non-sharable object built

Building sharable object onera_desp_lib_linux_x86_64.so
LAndI2Lstar.f:20680:19:

20680 |      &             maginput_tmp,Lm_tmp,XJ_tmp,Lstar_tmp)
      |                   1
Error: Actual argument contains too few elements for dummy argument 'maginput' (25/2500000) at (1)
sharable object built

Building sequence achieved
```

Even though the output claims that the objects were built, the files were not created (confirmed by running `find -name "onera_desp_lib_linux_x86_64*"`).

Edit: Now that I looked at your README.md PR, I see that I could use ENV=gfortran64. I tried that and it built without errors. Should we remove the gnu64 option from the `compile/Help.all` file?

Now the code gets hung up on the `make install` command. I am not sure if I should make a new issue, but my feeling is to keep to the same one.

```bash
$ make install
Installing
Creating .
mkdir -p ./matlab
Installing ./source/liboneradesp_. to .
cp ./source/liboneradesp_. .
cp: cannot stat './source/liboneradesp_.': No such file or directory
make: *** [Makefile:383: install.lib] Error 1
```

**Comment by AntoineBrunet** [comment]
Yes, I have the same issue with gnu64 environment. It works fine for me
with the gfortran64 environment though, so I put this one in the readme
file.

Le ven. 19 févr. 2021 à 21:05, Mykhaylo Shumko <notifications@github.com> a
écrit :

**Comment by mshumko** [comment]
Okay, with your updated install instructions in the README, the compilation succeeded. Thank you!

**Comment by mshumko** [comment]
The "Close with comment" did not do what I thought it would do. Hopefully you can still merge this PR after I reopened it.

**Review by mshumko — APPROVED** [review]

**Pull request merged**
