### PR TITLE
Reworked a cleaner Makefile, and corrected IDL wrappers

### PR DESCRIPTION
**Pull request by AntoineBrunet**
I'm sending this PR for review and remarks, even though some stuff is probably still missing here.

This PR cleans up the Makefile and correct the IDL wrappers. I should really have done it in two steps, but was working on the IDL wrappers first, which turn out to require some modification to the build process (as it includes a C shim for the wrapper). This PR mainly addresses issue #16 .

The new Makefile uses configurations in the `compile` directory, of the format `$(OS)-$(ENV).make`, which defines the compilers and options. I've added the linux64-gfortran64 and linux64-intel64 as examples, as they're the two compilers I have here. We should add more configuration files for each target architecture. I've done my best to not change the interface (so that the build process is unchanged), although there are a few differences:
    - now the simple `make` will build the library with gfortran by default
    - only shared library is built now. We can provide distinct configuration files for static build if someone needs it. 
    - I have also taken this opportunity to rename the output library `libirbem.so`, per standard naming conventions. If needed, we could make appropriate copy/links to the old names at install step.
 Install step is not implemented yet.

The IDL wrapper has been externalized in a single C interface file. Tested on GNU and Intel compilers on Linux.

- [x] Pull request has descriptive title
- [x] Pull request gives overview of changes
- [x] New code has inline comments where necessary
- [x] Appropriate documentation has been written
- [x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by mshumko** [comment]
Thanks for cleaning up the Makefile. It looks much more maintainable now. I got it to compile on both Linux and Mac using the default commands `make all` and `make install`. I slightly modified the python wrapper and it works as well.

However, I did see warnings when I ran `make all`.

**Linux**
```
gfortran -fpic -fno-second-underscore -std=legacy -ffixed-line-length-none -c -o bin/Mead_Tsyganenko.o source/Mead_Tsyganenko.f 
source/Mead_Tsyganenko.f:30:51:

   CALL get_Mead_Tsyganenko_coeffs(Lmc,fKp,S,A)
                                                   1
Warning: Type mismatch in argument ‘s’ at (1); passed REAL(4) to REAL(8) [-Wargument-mismatch]
````

```
source/find_bm.f:35:34:

        call find_bm_nalpha (xx0,1,alpha,Bposit,Bmir,xmin)
                                  1
Warning: Rank mismatch in argument ‘alpha’ at (1) (rank-1 and scalar) [-Wargument-mismatch]
```
and
```
source/LAndI2Lstar.f:20610:19:

      &             maginput_tmp,Lm_tmp,XJ_tmp,Lstar_tmp)
                   1
Warning: Actual argument contains too few elements for dummy argument ‘maginput’ (25/2500000) at (1) [-Wargument-mismatch]
```

**Mac OSX**
```
source/LAndI2Lstar.f:20610:19:
      &             maginput_tmp,Lm_tmp,XJ_tmp,Lstar_tmp)                   1Warning: Actual argument contains too few elements for dummy argument ‘maginput’ (25/2500000) at (1) [-Wargument-mismatch]
```

```
source/Mead_Tsyganenko.f:30:51:
   CALL get_Mead_Tsyganenko_coeffs(Lmc,fKp,S,A)                                                   1Warning: Type mismatch in argument ‘s’ at (1); passed REAL(4) to REAL(8) [-Wargument-mismatch]
```

```
source/find_bm.f:35:34:
        call find_bm_nalpha (xx0,1,alpha,Bposit,Bmir,xmin)                                  1Warning: Rank mismatch in argument ‘alpha’ at (1) (rank-1 and scalar) [-Wargument-mismatch]
```

```
source/onera_desp_lib.f:1666:22:
          DO J=1,9
                 2     
           Dens(J,I)=D(J)
                      1
Warning: Array reference at (1) out of bounds (9 > 8) in loop beginning at (2)
```
and many similar warnings in `shieldose2.f`
```
source/shieldose2.f:968:13:
       DO 10 J=1,N1
                  2
       D(J)=X(J+1)-X(J)
             1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
```

**Python**
Most tests failed when I ran the python test suite because the model outputs slightly changed. While the differences are relatively minor, I do wonder why they are different from previous versions of IRBEM. The test suite output is the same for Mac and Linux. Here is a part of the test output

```
======================================================================
FAIL: test_find_mirror_point (__main__.TestIRBEM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 146, in test_find_mirror_point
    self.assertAlmostEqualDict(self.model.find_mirror_point_output,
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 183, in assertAlmostEqualDict
    self.assertAlmostEqual(values, B[key])
AssertionError: 42271.69731031445 != 42262.312614335955 within 7 places (9.384695978493255 difference)

======================================================================
FAIL: test_footPoint (__main__.TestIRBEM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 118, in test_footPoint
    self.assertAlmostEqualDict(self.model.find_foot_point_output, foot_point_true_dict)
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 188, in assertAlmostEqualDict
    self.assertAlmostEqual(value_A, value_B)
AssertionError: 99.9906483758779 != 99.07260167773684 within 7 places (0.9180466981410547 difference)

======================================================================
FAIL: test_get_field_multi (__main__.TestIRBEM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 135, in test_get_field_multi
    self.assertAlmostEqualDict(self.model.get_field_multi_output,
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 188, in assertAlmostEqualDict
    self.assertAlmostEqual(value_A, value_B)
AssertionError: -21079.870874468797 != -21076.63920463125 within 7 places (3.231669837547088 difference)
======================================================================
FAIL: test_lstar_array (__main__.TestIRBEM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 89, in test_lstar_array
    self.assertAlmostEqualDict(self.model.make_lstar_output, array_true_dict)
  File "/home/mike/research/IRBEM_dev/IRBEM/python/IRBEM/test_IRBEM.py", line 188, in assertAlmostEqualDict
    self.assertAlmostEqual(value_A, value_B)
AssertionError: 3.5597506994978874 != 3.5579374952779204 within 7 places (0.0018132042199670018 difference)
```

**Comment by asherp** [comment]
Hey @mshumko  I'm curious what your setup was for Linux. I'm trying to build this branch in a docker container.

```console
make OS=linux64 ENV=gfortran64 all
/bin/sh: 1: [[: not found
/bin/sh: 1: [[: not found
http://irbem.svn.sourceforge.net/svnroot/irbem, http://irbem.svn.sourceforge.net/svnroot/irbem/???, NonSVN, Unknown
mv: cannot stat './source/myOwnMagField*.f': No such file or directory
mv: cannot stat './src_desp/myOwnMagField*.f': No such file or directory
make: *** [Makefile:466: myOwnMagField1] Error 1
```

**Comment by mshumko** [comment]
@asherp, are you in the right branch? When I clone the [code](https://github.com/AntoineBrunet/IRBEM/tree/new_idl_wrappers),  by default it checks out the `main` branch---in which I got the same error when I ran the `make` commands. However, when I switch from the `main` branch to `new_idl_wrappers` branch, the compilation succeeded (with plenty of Fortran warnings about misshapen arrays).

By the SVN reference in your error, my guess is that the `main` branch in @AntoineBrunet's forked repo is out-of-date with https://github.com/PRBEM/IRBEM/tree/main.

**Comment by asherp** [comment]
> @asherp, are you in the right branch? When I clone the [code](https://github.com/AntoineBrunet/IRBEM/tree/new_idl_wrappers), by default it checks out the `main` branch---in which I got the same error when I ran the `make` commands. However, when I switch from the `main` branch to `new_idl_wrappers` branch, the compilation succeeded (with plenty of Fortran warnings about misshapen arrays).
> 
> By the SVN reference in your error, my guess is that the `main` branch in @AntoineBrunet's forked repo is out-of-date with https://github.com/PRBEM/IRBEM/tree/main.

Thank You. I somehow installed it through spacepy, but if I need an independent container for just IRBEM I'll use this.

**Review by mshumko — COMMENTED** [review]
This looks okay to me, but since the `.so` file is now saved in `IRBEM/` and not `IRBEM/source/`, the Python wrapper does not run correctly. The fix is simple, and maybe its easiest if you add one more commit. 

You'll need to remove the `source` part of [this path](https://github.com/AntoineBrunet/IRBEM/blob/e09247a34b90e0c6c9860daaeb04961f599641ca/python/IRBEM/IRBEM.py#L106) so the line should be `'..', '..'))`

**Comment by AntoineBrunet** [comment]
@mshumko Thanks I've updated the default path, so that the wrappers looks for the `.so` file in the root directory. I think it's best if the Makefile does not modify any file in the `source` directory at all.

**Review by mshumko — APPROVED** [review]
Looks good!

One comment regarding the `.make` files in the `compile` directory: do we need to write one for Windows, and should we create an alias for OSX that uses the same Linux compiler options?

**Comment by AntoineBrunet** [comment]
Hi, sorry for the long delay, I just got back from paternity leave. To create new aliases or environment is pretty straightforward, you just have to add a new .make file to the compile directory. This file could be a symlink to the Linux one, or a copy of we expect the options to change between the two systems.

**Comment by mshumko** [comment]
Congratulations and welcome back @AntoineBrunet! 

I have not looked at how to make the necessary aliases or environments myself, but ultimately the makefile will need to call `gfortran-12` (or another version of gfortan that [GitHub Actions supports](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#language-and-runtime)). Feel free to add that alias if it is easy for you now, but I can also look into it after the holidays.

Considering all of the changes you've made so far, I suggest that we merge this PR as is and then create a new PR with the alias and CI test for OSX.

**Comment by AntoineBrunet** [comment]
Thanks @mshumko . I went ahead and merged the PR. There was an issue which prevented the rebase merge, I think it was due to a previous PR where I did something wrong before merging. Hopefully at some point we can have a cleaner rebase merge process.
I've raised a new issue for the creation of the Windows and OSx configurations.

**Pull request merged**
